os: osx
osx_image: xcode8.3
language: objective-c

before_install:
 - gem install cocoapods --pre --quiet
 - gem install slather
script:
  - xcodebuild -workspace Bulldog Bucks.xcworkspace -scheme Bulldog Bucks -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -configuration Debug -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES build test -quiet
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f cobertura.xml -X coveragepy -X gcov -X xcode -t $CODECOV_TOKEN
